; ZX81 Characters.
_QT  EQU  $0B  ;" quote
_PD  EQU  $0C  ;£ pound symbol
_SD  EQU  $0D  ;$ dollar
_CL  EQU  $0E  ;: colon
_QM  EQU  $0F  ;? question
_OP  EQU  $10  ;( open paren
_CP  EQU  $11  ;) close paren
_GT  EQU  $12  ;> greater than
_LT  EQU  $13  ;< less than
_EQ  EQU  $14  ;= equal
_PL  EQU  $15  ;+ plus
_MI  EQU  $16  ;- minus
_AS  EQU  $17  ;* asterisk
_SL  EQU  $18  ;/ slash
_SC  EQU  $19  ;; semi-colon
_CM  EQU  $1A  ;, comma
_DT  EQU  $1B  ;. dot
_FS  EQU  $1B  ;. full stop/period
_NL  EQU  $76  ;NEWLINE

__   EQU  $00  ;space
_0   EQU  $1C
_1   EQU  $1D
_2   EQU  $1E
_3   EQU  $1F
_4   EQU  $20
_5   EQU  $21
_6   EQU  $22
_7   EQU  $23
_8   EQU  $24
_9   EQU  $25
_A   EQU  $26
_B   EQU  $27
_C   EQU  $28
_D   EQU  $29
_E   EQU  $2A
_F   EQU  $2B
_G   EQU  $2C
_H   EQU  $2D
_I   EQU  $2E
_J   EQU  $2F
_K   EQU  $30
_L   EQU  $31
_M   EQU  $32
_N   EQU  $33
_O   EQU  $34
_P   EQU  $35
_Q   EQU  $36
_R   EQU  $37
_S   EQU  $38
_T   EQU  $39
_U   EQU  $3A
_V   EQU  $3B
_W   EQU  $3C
_X   EQU  $3D
_Y   EQU  $3E
_Z   EQU  $3F
_a   EQU  $A6
_b   EQU  $A7
_c   EQU  $A8
_d   EQU  $A9
_e   EQU  $AA
_f   EQU  $AB
_g   EQU  $AC
_h   EQU  $AD
_i   EQU  $AE
_j   EQU  $AF
_k   EQU  $B0
_l   EQU  $B1
_m   EQU  $B2
_n   EQU  $B3
_o   EQU  $B4
_p   EQU  $B5
_q   EQU  $B6
_r   EQU  $B7
_s   EQU  $B8
_t   EQU  $B9
_u   EQU  $BA
_v   EQU  $BB
_w   EQU  $BC
_x   EQU  $BD
_y   EQU  $BE
_z   EQU  $BF